NoteA/models.py
from app import db
from datetime import datetime
from flask_login import UserMixin
from sqlalchemy.orm import backref
from werkzeug.security import generate_password_hash, check_password_hash


class TimestampMixin(object):
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, onupdate=datetime.utcnow)


class Task(db.Model):
    __tablename__ = 'task'
    id = db.Column(db.Integer, primary_key=True)
    taskname = db.Column(db.String(75))
    duedate = db.Column(db.DateTime)
    """ User_id Foreign Key """
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    user_task = db.relationship("User",backref=backref("user_task", uselist=False) )

    def __init__(self, taskname, duedate, user_id):
        self.taskname = taskname
        self.duedate = duedate
        self.user_id = user_id

    def __repr__(self):
        return f"<Task {self.taskname}>"


class User(db.Model, UserMixin, TimestampMixin):
    __tablename__ = 'user'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(50))
    password = db.Column(db.String(20))

    def __init__(self, username, password):
        self.username = username
        self.password = password

    def __repr__(self):
        return f"<Task {self.username}>"

    # check user password is correct
    def check_password(self, password):
        print(f"check_password 1 [{self.password}] [{password}]")
        return check_password_hash(self.password, password)


class Note(db.Model, TimestampMixin):
    __tablename__ = 'note'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(200))
    content = db.Column(db.String(10000))
    """ User_id Foreign Key """
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    user_note = db.relationship("User",backref=backref("user_note", uselist=False) )

    """ contentsnip takes the note content data from the database and shortens it for main page display """
    @ property
    def contentsnip(self):
        return self.content[:10]

    def __init__(self, title, content, user_id):
        self.title = title
        self.content = content
        self.user_id = user_id

    def __repr__(self):
        return f"<Task {self.title}>"

NoteA/app.py
import os
import yaml #Importing a file format for app config
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

def read_config(appconfig):
    if os.path.isfile(appconfig):
        with open(appconfig, 'r', encoding="utf-8") as config_file:
            return yaml.safe_load(config_file)
    return {}

NoteA_config = read_config('NoteA_config.yaml')

NoteA = Flask(__name__)
NoteA.config ['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///website.db'
NoteA.config ['SECRET_KEY'] = NoteA_config['NoteA']['security']['key']

db = SQLAlchemy(NoteA)
migrate = Migrate(NoteA, db)

NoteA/routes.py
from flask import Blueprint, render_template, session, redirect
from models import Task, Note, User
from auth.forms import UserChangePassword

web = Blueprint("web", __name__, template_folder="templates")


@web.route("/Home", methods=["GET", "POST"])
def Home():
    id = session.get('user_id')
    if id is None:
        return redirect('/Login')
    """ Content is filtered by current user id in session which matches items in database. """
    tasks = Task.query.filter(Task.user_id == id)
    notes = Note.query.filter(Note.user_id == id)
    return render_template("Main/main_page.html", title="Home", tasks=tasks, notes=notes)

@web.route("/Account_Settings", methods=["GET", "POST"])
def Account_Settings():
    passwordform = UserChangePassword()
    return render_template("Login and Accounts/Account/settings.html", title="Settings", passwordform=passwordform)


@web.route("/Create_Note", methods=["GET", "POST"])
def Create_Note():
    return render_template("Notes/create_note.html", title="Create Note")

NoteA/templates/Login and Accounts/Account/settings.html
{% extends "base.html" %}
{% import 'Login and Accounts/wtf.html' as wtfx %}

{% block styles %}
<link href="static/css/accountpage.css" rel="stylesheet">
<link href="static/media/loginmedia.css" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="grid-container">

    <section class="setting">
        <div class="button-menu-left">
            <form action="{{ url_for('web.Home')}}">
                <button class="button" type=submit>Back</button>
            </form>
        </div>
        <hr>
        <div class="password-form">
            <h4>Change Password:</h4>
            <form action="/Change_Password" method="POST">
                {{ passwordform.hidden_tag() }}
                {{ wtfx.form_field(passwordform.CurrentPassword, id='font', placeholder=" Old Password") }}
                {{ wtfx.form_field(passwordform.NewPassword, id='font', placeholder=" New Password") }}
                {{ wtfx.form_field(passwordform.NewPasswordRetype, id='font', placeholder="Retype Password") }}
                {{ wtfx.form_field(passwordform.PasswordUpdate) }}
            </form>
        </div>
        <hr>
        <h4> Delete Data</h4>
        <p>
            <bold>Warning!</bold>
            This is an Irreversible action!
        </p>
        <p>
            All Notes and To-Do Tasks will be deleted and non-recovereable.
        </p>
        <form action="/Delete_User" method="POST">
            <button class="button" type="submit">Delete Data</button>
        </form>

    </section>

</div>
{% endblock %}

NoteA/templates/Login and Accounts/create_account.html
{% extends "base.html" %}
{% import 'Login and Accounts/wtf.html' as wtfx %}

{% block styles %}
    <link href="static/css/loginpage.css" rel="stylesheet">
    <link href="static/css/media/loginmedia.css" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="grid-container">

    <section class="loginspace">
        <img src="{{url_for('static', filename='images/Note Armadillo.png')}}" alt="Logo">
        <section>
            <form action="" method="POST">
                <p>Please input a username and password <br>into the required fields.
                <p class="list">Password must be between 8 & 20 characters</p>
                </p>
                {{ accform.hidden_tag() }}
                {{ wtfx.form_field(accform.Username, id='font', placeholder="Username") }}
                {{ wtfx.form_field(accform.Password, id='font', placeholder="Password") }}
                {{ wtfx.form_field(accform.PasswordRetype, id='font', placeholder="Retype Password") }}
                {{ wtfx.form_field(accform.CreateAccount) }}
            </form>
        </section>
    </section>

</div>
{% endblock %}

NoteA/templates/Login and Accounts/login.html
{% extends "base.html" %}
{% import 'Login and Accounts/wtf.html' as wtfx %}

{% block styles %}
    <link href="static/css/loginpage.css" rel="stylesheet">
    <link href="static/css/media/loginmedia.css" rel="stylesheet">

{% endblock %}

{% block content %}
<div class="grid-container">
    <section class="loginspace">
        <img src="{{url_for('static', filename='images/Note Armadillo.png')}}" alt=" Armadillo Logo">
        <p>
            All your notes securely in one place.<br>
            You hold all your data. No online<br>
            servers required.
        </p>
        <section>
            <form action="/Login" method="POST" aria-label="Login Form">
                {{ loginform.hidden_tag() }}
                <label type="hidden_tag" aria-label="Username input below"></label>
                {{ wtfx.form_field(loginform.Username, id='font', placeholder="Username") }}
                <label type="hidden_tag" aria-label="Password input below"></label>
                {{ wtfx.form_field(loginform.Password, id='font', placeholder="Password") }}
                <label type="hidden_tag" aria-label="Submit button below"></label>
                {{ wtfx.form_field(loginform.Login, class='button') }}
            </form>


                <hr>
                <form action="{{ url_for('data.CreateAccountRoot')}}">
                    <button type=submit aria-label="Create Account button" class="button">Create Account</button>
                </form>

        </section>
    </section>
</div>
{% endblock %}

NoteA/templates/Login and Accounts/wtf.html
{% macro form_errors(form, hiddens=True) %}
  {%- if form.errors %}
    {%- for fieldname, errors in form.errors.items() %}
      {%- if bootstrap_is_hidden_field(form[fieldname]) and hiddens or
             not bootstrap_is_hidden_field(form[fieldname]) and hiddens != 'only' %}
        {%- for error in errors %}
          <p class="error">{{error}}</p>
        {%- endfor %}
      {%- endif %}
    {%- endfor %}
  {%- endif %}
{%- endmacro %}

{% macro _hz_form_wrap(horizontal_columns, form_type, add_group=False, required=False) %}
{% if form_type == "horizontal" %}
  {% if add_group %}<div class="form-group{% if required %} required{% endif %}">{% endif %}
  <div class="col-{{horizontal_columns[0]}}-offset-{{horizontal_columns[1]}}
              col-{{horizontal_columns[0]}}-{{horizontal_columns[2]}}
             ">
{% endif %}
{{caller()}}

{% if form_type == "horizontal" %}
  {% if add_group %}</div>{% endif %}
  </div>
{% endif %}
{% endmacro %}

{% macro form_field(field,
                    form_type="basic",
                    horizontal_columns=('lg', 2, 10),
                    button_map={}) %}

{# this is a workaround hack for the more straightforward-code of just passing required=required parameter. older versions of wtforms do not have
the necessary fix for required=False attributes, but will also not set the required flag in the first place. we skirt the issue using the code below #}
{% if field.flags.required and not required in kwargs %}
{% set kwargs = dict(required=True, **kwargs) %}
{% endif %}

{% if field.widget.input_type == 'checkbox' %}
  {% call _hz_form_wrap(horizontal_columns, form_type, True, required=required) %}
    <div class="checkbox">
      <label>
        {{field()|safe}} {{field.label.text|safe}}
      </label>
    </div>
  {% endcall %}
{%- elif field.type == 'RadioField' -%}
  {# note: A cleaner solution would be rendering depending on the widget,
     this is just a hack for now, until I can think of something better #}
  {% call _hz_form_wrap(horizontal_columns, form_type, True, required=required) %}
    {% for item in field -%}
      <div class="radio">
        <label>
          {{item|safe}} {{item.label.text|safe}}
        </label>
      </div>
    {% endfor %}
  {% endcall %}
{%- elif field.type == 'SubmitField' -%}
  {# deal with jinja scoping issues? #}
  {% set field_kwargs = kwargs %}

  {# note: same issue as above - should check widget, not field type #}
  {% call _hz_form_wrap(horizontal_columns, form_type, True, required=required) %}
    {{field(class='btn btn-%s' % button_map.get(field.name, 'default'),
            **field_kwargs)}}
  {% endcall %}
{%- elif field.type == 'FormField' -%}
{# note: FormFields are tricky to get right and complex setups requiring
   these are probably beyond the scope of what this macro tries to do.
   the code below ensures that things don't break horribly if we run into
   one, but does not try too hard to get things pretty. #}
  <fieldset>
    <legend>{{field.label}}</legend>
    {%- for subfield in field %}
      {% if not bootstrap_is_hidden_field(subfield) -%}
        {{ form_field(subfield,
                      form_type=form_type,
                      horizontal_columns=horizontal_columns,
                      button_map=button_map) }}
      {%- endif %}
    {%- endfor %}
  </fieldset>
{% else -%}
  <div class="form-group {% if field.errors %} has-error{% endif -%}
                         {%- if field.flags.required %} required{% endif -%}
  ">
      {%- if form_type == "inline" %}
        {{field.label(class="sr-only")|safe}}
        {% if field.type == 'FileField' %}
          {{field(**kwargs)|safe}}
        {% else %}
          {{field(class="form-control", **kwargs)|safe}}
        {% endif %}
      {% elif form_type == "horizontal" %}
        {{field.label(class="control-label " + (
          " col-%s-%s" % horizontal_columns[0:2]
        ))|safe}}
        <div class=" col-{{horizontal_columns[0]}}-{{horizontal_columns[2]}}">
          {% if field.type == 'FileField' %}
            {{field(**kwargs)|safe}}
          {% else %}
            {{field(class="form-control", **kwargs)|safe}}
          {% endif %}
        </div>
        {%- if field.errors %}
          {%- for error in field.errors %}
            {% call _hz_form_wrap(horizontal_columns, form_type, required=required) %}
              <p class="help-block">{{error}}</p>
            {% endcall %}
          {%- endfor %}
        {%- elif field.description -%}
          {% call _hz_form_wrap(horizontal_columns, form_type, required=required) %}
            <p class="help-block">{{field.description|safe}}</p>
          {% endcall %}
        {%- endif %}
      {%- else -%}
        {{field.label(class="control-label")|safe}}
        {% if field.type == 'FileField' %}
          {{field(**kwargs)|safe}}
        {% else %}
          {{field(class="form-control", **kwargs)|safe}}
        {% endif %}

        {%- if field.errors %}
          {%- for error in field.errors %}
            <p class="help-block">{{error}}</p>
          {%- endfor %}
        {%- elif field.description -%}
          <p class="help-block">{{field.description|safe}}</p>
        {%- endif %}
      {%- endif %}
  </div>
{% endif %}
{% endmacro %}

{# valid form types are "basic", "inline" and "horizontal" #}
{% macro quick_form(form,
                    action="",
                    method="post",
                    extra_classes=None,
                    role="form",
                    form_type="basic",
                    horizontal_columns=('lg', 2, 10),
                    enctype=None,
                    button_map={},
                    id="",
                    novalidate=False) %}
{#-
action="" is what we want, from http://www.ietf.org/rfc/rfc2396.txt:

4.2. Same-document References

   A URI reference that does not contain a URI is a reference to the
   current document.  In other words, an empty URI reference within a
   document is interpreted as a reference to the start of that document,
   and a reference containing only a fragment identifier is a reference
   to the identified fragment of that document.  Traversal of such a
   reference should not result in an additional retrieval action.
   However, if the URI reference occurs in a context that is always
   intended to result in a new request, as in the case of HTML's FORM
   element, then an empty URI reference represents the base URI of the
   current document and should be replaced by that URI when transformed
   into a request.

 -#}
{#- if any file fields are inside the form and enctype is automatic, adjust
    if file fields are found. could really use the equalto test of jinja2
    here, but latter is not available until 2.8

    warning: the code below is guaranteed to make you cry =(
#}
{%- set _enctype = [] %}
{%- if enctype is none -%}
  {%- for field in form %}
    {%- if field.type == 'FileField' %}
      {#- for loops come with a fairly watertight scope, so this list-hack is
          used to be able to set values outside of it #}
      {%- set _ = _enctype.append('multipart/form-data') -%}
    {%- endif %}
  {%- endfor %}
{%- else %}
  {% set _ = _enctype.append(enctype) %}
{%- endif %}
<form
  {%- if action != None %} action="{{action}}"{% endif -%}
  {%- if id %} id="{{id}}"{% endif -%}
  {%- if method %} method="{{method}}"{% endif %}
  class="form
    {%- if extra_classes %} {{extra_classes}}{% endif -%}
    {%- if form_type == "horizontal" %} form-horizontal
    {%- elif form_type == "inline" %} form-inline
    {%- endif -%}
  "
  {%- if _enctype[0] %} enctype="{{_enctype[0]}}"{% endif -%}
  {%- if role %} role="{{role}}"{% endif -%}
  {%- if novalidate %} novalidate{% endif -%}
  >
  {{ form.hidden_tag() }}
  {{ form_errors(form, hiddens='only') }}

  {%- for field in form %}
    {% if not bootstrap_is_hidden_field(field) -%}
      {{ form_field(field,
                    form_type=form_type,
                    horizontal_columns=horizontal_columns,
                    button_map=button_map) }}
    {%- endif %}
  {%- endfor %}

</form>
{%- endmacro %}

NoteA/templates/Main/main_page.html
{% extends "base.html" %}

{% block styles %}
<link href="static/css/mainpage.css" rel="stylesheet">
<link href="static/media/mainpagemedia.css" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="grid-container">
  <section class="menu">
    <div class="button-menu">
      <a class="button" href="{{ url_for('web.Create_Note')}}">New Note</a>
      <a class="button" href="/Account_Settings"> Account Settings</a>
      <a class="button" href="{{ url_for('data.Logout')}}"> Logout</a>
    </div>
  </section>

  <section class="todo">
    {% for task in tasks %}
    <div class="task-element">
      <ol>
        <li class="tasks">
          {{ task.taskname }}
          <p></p>
          {{ task.duedate.strftime('%d-%m-%Y %H:%M:%S') }}
        </li>

        <li class="task-button">
          <form class="deletetask" action="/Delete_Task/{{task.id}}" method="POST">
            <button class="button" type="submit"><i class="fa-solid fa-trash-can"></i></button>
          </form>
        </li>
      </ol>
    </div>
    {% endfor %}
  </section>

  <section class="todoform">
    <form action="/Add_Task" method="POST">
      <input type="text" name="taskname" placeholder="To-Do Task Name" required="required">
      <br>
      <input type="datetime-local" name="duedate" placeholder="Due date DD/MM/YYYY" required="required">
      <br>
      <button type="submit" class="button">Add To-Do Task</button>
    </form>
  </section>

  <section class="note">
    {% for note in notes %}
    <div class="note-element">
      <ol class="notes">
        <li class="notetitle">
          <a href="/View_Note/{{note.id}}">{{ note.title }}</a>
        </li>
        <li class="notes">
          {{ note.contentsnip }}
        </li>
      </ol>

      <ol class="created-time">
        <li>
          {{ note.created_at.strftime('%d-%m-%Y %H:%M:%S') }}
        </li>
        <br>
      </ol>

      <ol class="buttons">
        <form class="edit-note" action="/Edit_Note/{{note.id}}" method="POST" aria-label="Edit Note Button Container">
          <button class="button" type="submit"><i class="fa-solid fa-pencil"></i></button>
        </form>

        <form class="delete-note" action="/Delete_Note/{{note.id}}" method="POST"
          aria-label="Delete Note Button Container">
          <button class="button" type="submit"><i class="fa-solid fa-trash-can"></i></button>
        </form>
      </ol>
    </div>
    {% endfor %}
  </section>

</div>
{% endblock %}

NoteA/templates/Notes/create_note.html
{% extends "base.html" %}

{% block styles %}
<link href="static/css/notepage.css" rel="stylesheet">

{% endblock %}

{% block content %}
<div class="grid-container">
  <section class="header">
    <form action="/Account_Settings">
      <button class="button" type="submit">Account Settings</button>
    </form>
  </section>

  <section class="buttonmenu">
    <form action="/Home">
      <button class="button" role="button">Back</button>
    </form>
  </section>

  <section class="main">
    <form action="/Add_Note" method="POST">
      <input type="text" name="title" class="title" placeholder="Title.." required="required">
      <br>
      <textarea type="text" name="content" class="content" placeholder="Type here..." required="required" cols="70"
        rows="26"></textarea>
      <br>
      <button type="submit" class="button">Create Note</button>
    </form>
  </section>

</div>
{% endblock %}

NoteA/templates/Notes/edit_note.html
{% extends "base.html" %}

{% block styles %}
<link href="{{url_for('static', filename='css/notepage.css')}}" rel="stylesheet">
<link href="{{url_for('static', filename='css/base.css')}}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="grid-container">
  <section class="header">
    <form action="/Account_Settings">
      <button class="button" type="submit">Account Settings</button>
    </form>
  </section>

  <section class="buttonmenu">
    <form action="/Home">
      <button class="button" role="button">Back</button>
    </form>
  </section>

  <section class="main">
    <form class="deletenote" action="/Update_Note/{{note.id}}" method="post">
      <input type="text" aria-label="Edit Note Title" name="title" class="title" value="{{ note.title }}"
      required="required">
      <br>
      <textarea type="text" aria-label="Edit Note Contents" name="content" class="content" required="required" cols="70"
        rows="26">{{ note.content }}</textarea>
      <br>
      <button class="button" role="button"> Update Note</button>
    </form>
<!--     <form action="/Update_Note/{{note.id}}">
      <input type="text" aria-label="Edit Note Title" name="title" class="title" value="{{ note.title }}"
        required="required">
      <br>
      <textarea type="text" aria-label="Edit Note Contents" name="content" class="content" required="required" cols="70"
        rows="26">{{ note.content }}</textarea>
      <br>
      <button type="submit" class="button">Save Changes</button>
    </form> -->

    <form action="/View_Note/{{note.id}}">
      <button class="button" role="button">Discard Changes</button>
    </form>
  </section>

</div>
{% endblock %}

NoteA/templates/Notes/view_note.html
{% extends "base.html" %}

{% block styles %}
<link href="{{url_for('static', filename='css/notepage.css')}}" rel="stylesheet">
<link href="{{url_for('static', filename='css/base.css')}}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="grid-container">

  <section class="header">
    <form action="/Account_Settings">
      <button class="button" type="submit">Account Settings</button>
    </form>
  </section>

  <section class="buttonmenu">
    <form action="/Home">
      <button class="button" role="button">Back</button>
    </form>
  </section>

  <section class="main">
    <div class="note-element">
      <div class="title">
        <h4>{{ note.title }}</h4>
      </div>
      <div class="date">
        <h5> Created at: {{ note.created_at.strftime('%d-%m-%Y %H:%M:%S') }}</h5>
        <br>
        {% if note.updated_at is not none %}
        <h5> Updated at: {{ note.updated_at.strftime('%d-%m-%Y %H:%M:%S') }}</h5>
        {% else %}
        <h5> Updated at: Never</h5>
        {% endif %}
      </div>
      <hr>
      <div class="note-content">
        <p> {{ note.content }}</p>
      </div>

      <div class="buttongroup">
        <form class="editnote" action="/Edit_Note/{{note.id}}" method="post">
          <button class="button" role="button">Edit Note</button>
        </form>

        <form class="deletenote" action="/Delete_Note/{{note.id}}" method="post">
          <button class="button" role="button"> Delete Note</button>
        </form>
      </div>
    </div>
  </section>
</div>
{% endblock %}

NoteA/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block styles %}{% endblock %}
    <title>Note Armadillo</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.ico')}}">
    <script src="https://kit.fontawesome.com/c3f98b7b36.js" crossorigin="anonymous"></script>
    <link href="static/css/base.css" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>


<body>
    <!-- For message flashes in response to system processes, validation and input -->
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert" id="alert">
                {{ message }}
            </div>
            {% endfor %}
        {% endif %}
    {% endwith %}

    {% block content %}

    {% endblock %}

</body>

{% block scripts %}
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script>

    setTimeout(function() {
        $('#alert').remove();
        console.log("timeout")
    }, 9000);
</script>
{% endblock %}

</html>